model = "gpt-5.2-codex"
model_reasoning_effort = "high"
network_access = true
sandbox_mode = "workspace-write"
approval_policy = "never"
web_search_request = true

[projects."~/ghq/github.com/supermomonga/hft-research"]
trust_level = "trusted"

[profiles.terminal-command]
model = "gpt-5"
model_reasoning_effort = "low"
network_access = false
sandbox_mode = "read-only"
approval_policy = "on-request"

[notice]
"hide_gpt-5.1-codex-max_migration_prompt" = true

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"

