# Machine-global config

[tools]
# Runtime
bun = "latest"
deno = "latest"
go = "latest"
python = "latest"
rust = "latest"

# Tools
chezmoi = "latest"
neovim = "latest"
fzf = "latest"
uv = "latest"

# Packages
"go:github.com/x-motemen/ghq" = "latest"
"pipx:edge-tts" = "latest"
